#!/usr/bin/env bash
figlet repoclean
# Bersihkan Index Section Import Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
# Bersihkan Index Section Main Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
# Bersihkan Index Section Queen Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
# Bersihkan Index Section Resticted Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
# Bersihkan Index Section Upstream Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
