#!/usr/bin/env bash
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# .
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# .
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

figlet repoclean
# Bersihkan Index Section Import Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
# Bersihkan Index Section Main Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
# Bersihkan Index Section Queen Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
# Bersihkan Index Section Resticted Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
# Bersihkan Index Section Upstream Xenta OS Repository
rm -rf main/*/*.deb
rm -rf main/*/*.dsc
rm -rf main/*/*.tar.xz
rm -rf main/*/*.build
