#!/usr/bin/env bash
figlet repoindex
# Membuat Index Section Import Xenta OS Repository
reprepro -Vb . -C import includedeb arok import/**/*.deb
reprepro -Vb . -C import include arok import/**/*.changes
# Membuat Index Section Main Xenta OS Repository
reprepro -Vb . -C main includedeb arok main/**/*.deb
reprepro -Vb . -C main include arok main/**/*.changes
# Membuat Index Section Queen Xenta OS Repository
reprepro -Vb . -C queen includedeb arok queen/**/*.deb
reprepro -Vb . -C queen include arok queen/**/*.changes
# Membuat Index Section Resticted Xenta OS Repository
reprepro -Vb . -C restricted includedeb arok resticted/**/*.deb
reprepro -Vb . -C restricted include arok resticted/**/*.changes
# Membuat Index Section Upstream Xenta OS Repository
reprepro -Vb . -C upstream includedeb arok upstream/**/*.deb
reprepro -Vb . -C upstream include arok upstream/**/*.changes
