#!/usr/bin/env bash
figlet repoindex
# Membuat Index Section Import Repository
reprepro -Vb  . includedeb arok import/**/*.deb
reprepro -Vb  . include arok import/**/*.changes
# Membuat Index Section Main Repository
reprepro -Vb  . includedeb arok main/**/*.deb
reprepro -Vb  . include arok main/**/*.changes
# Membuat Index Section Queen Repository
reprepro -Vb  . includedeb arok queen/**/*.deb
reprepro -Vb  . include arok queen/**/*.changes
# Membuat Index Section Resticted Repository
reprepro -Vb  . includedeb arok resticted/**/*.deb
reprepro -Vb  . include arok resticted/**/*.changes
# Membuat Index Section Upstream Repository
reprepro -Vb  . includedeb arok upstream/**/*.deb
reprepro -Vb  . include arok upstream/**/*.changes
