#!/usr/bin/env bash
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# .
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# .
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

figlet repoindex
# Membuat Index Section Import Xenta OS Repository
# reprepro -Vb . -C import includedeb         arok import/**/*.deb
# reprepro -Vb . -C import include            arok import/**/*.changes

# Membuat Index Section Main Xenta OS Repository
reprepro -Vb . -C main includedeb           arok main/p/paketku/*.deb
reprepro -Vb . -C main includedeb           arok main/x/xentasystem/*.deb
reprepro -Vb . -C main includedeb           arok main/x/xenta-x-icons/*.deb
reprepro -Vb . -C main include              arok main/p/paketku/*.changes
reprepro -Vb . -C main include              arok main/x/xentasystem/*.changes
reprepro -Vb . -C main include              arok main/x/xenta-x-icons/*.changes

# Membuat Index Section Queen Xenta OS Repository
# reprepro -Vb . -C queen includedeb          arok queen/**/*.deb
# reprepro -Vb . -C queen include             arok queen/**/*.changes

# Membuat Index Section Resticted Xenta OS Repository
# reprepro -Vb . -C restricted includedeb     arok resticted/**/*.deb
# reprepro -Vb . -C restricted include        arok resticted/**/*.changes

# Membuat Index Section Upstream Xenta OS Repository
# reprepro -Vb . -C upstream includedeb       arok upstream/**/*.deb
# reprepro -Vb . -C upstream include          arok upstream/**/*.changes
